### ISSUE TITLE
php-fpm模式下如何进行监控？ 

### ISSUE THREAD

**Issue by longhtml** [chuan-yun/Molten#10]
php-fpm模式下如何进行监控？

**Comment by silkcutKs** [comment]
请看wiki：
https://github.com/chuan-yun/Molten/wiki/%E8%8E%B7%E5%8F%96molten%E7%8A%B6%E6%80%81

**Comment by longhtml** [comment]
php.ini文件配置以下内容即可。  

extension = molten.so
molten.enable=1
molten.service_name=default
molten.tracing_cli=1
molten.sampling_type=2
molten.sampling_request=10
molten.report_interval=10
molten.report_limit=100
molten.sink_type=4
molten.sink_http_uri=http://127.0.0.1:9411/api/v1/spans
molten.span_format=zipkin
