### ISSUE TITLE
traceId 获取

### ISSUE THREAD

**Issue by xinshengsiyu** [chuan-yun/Molten#100]
考虑到我现在的业务场景，如果能在PHP里面获取的traceid返回给第三方调用方的就更好了。但是好像没有找到获取traceId的方法

**Comment by silkcutKs** [comment]
@xinshengsiyu  你的第三方的调用是什么？  能够列一下吗?

**Comment by xinshengsiyu** [comment]
就是API接口，如果能在接口中返回traceid查问题就更方便了

**Comment by silkcutKs** [comment]
@xinshengsiyu http的api接口会在header带上相应的tracce信息。你可以在被调用端打印出来的。

**Comment by xinshengsiyu** [comment]
可能我没表达清楚，我想让我的上游获取到traceid。比如有个 client，调用了我的PHP接口，我通过接口返回类似{"traceId":123},当发现结果不符合预期的时候。client可以通过traceid追踪一下。所以我需要在我的php代码中获取到traceid返回给我的上游

**Comment by silkcutKs** [comment]
你的意思是说在返回的header信息中添加trace相关的信息吗？？

**Comment by silkcutKs** [comment]
@xinshengsiyu 好奇的问一下， java那边是使用agent？

**Comment by xinshengsiyu** [comment]
@silkcutKs 唉，评审没过。PHP真不行了，我准备转go了。受气

**Comment by silkcutKs** [comment]
_php还能再战一万年！！！
