### ISSUE TITLE
调用其他服务的 http 接口时，curl可以正常跟踪到后续服务，file_get_contents 好像不行?

### ISSUE THREAD

**Issue by yanghahaha** [chuan-yun/Molten#102]
我用curl方式调用本机的另一个php接口，可以正常的跟踪到另一个php-service
$ch = curl_init('http://127.0.0.1/api/ListUser');
curl_exec($ch);

如果用file_get_contents方式，则只会记录一个file_get_contents，没有另一个php-service的信息
file_get_contents('http://127.0.0.1/api/ListUser');

**Comment by silkcutKs** [comment]
file_get_contents 现在不支持链路串联
想进行链路串联的话， 最好使用curl

**Comment by yanghahaha** [comment]
明白了，这样的话，已有项目可能需要修改。
