### ISSUE TITLE
获取molten状态失败

### ISSUE THREAD

**Issue by longhtml** [chuan-yun/Molten#11]
http://127.0.0.1:9411/zipkin/  可以运行起来。 

使用以下URL路径 ，获取molten状态失败。
http://127.0.0.1:9411/zipkin/molten/status
http://127.0.0.1:9411/molten/status
http://127.0.0.1/molten/status
http://127.0.0.1/zipkin/molten/status

求解， 谢谢！

**Comment by silkcutKs** [comment]
想要获取molten的运行状态， 需要启动 cgi-server, 采用php-fpm/php-cgi 均可。

![image](https://user-images.githubusercontent.com/9278779/28995654-68438b1c-7a21-11e7-8cb5-0cca7d4d1d57.png)

比如我启动是php-fpm， 使用如下的nginx配置就ok。比较类似与php-fpm status的使用方式

server {
     listen       8899;
     server_name  192.168.56.10;

     location ~ status$ {
         include fastcgi_params;
         fastcgi_param SCRIPT_FILENAME $fastcgi_script_name;
         fastcgi_pass   127.0.0.1:9000;
     }
 }

**Comment by silkcutKs** [comment]
请看wiki：
https://github.com/chuan-yun/Molten/wiki/%E8%8E%B7%E5%8F%96molten%E7%8A%B6%E6%80%81

**Comment by longhtml** [comment]
完美解決問題。 非常感謝！
