### ISSUE TITLE
微信群二维码已经过期了可以更新下吗？

### ISSUE THREAD

**Issue by wasabihu** [chuan-yun/Molten#151]
这里的二维码:
https://github.com/chuan-yun/Molten/wiki/%E5%8A%A0%E5%85%A5%E6%88%91%E4%BB%AC

**Comment by silkcutKs** [comment]
![3851580701285_ pic](https://user-images.githubusercontent.com/9278779/73624071-5c7ef500-467a-11ea-94a1-a03219df48fd.jpg)

**Comment by wasabihu** [comment]
谢谢，已经进去了~
