### ISSUE TITLE
是否支持phalcon+swoole模式的应用？是否与其他扩展冲突？

### ISSUE THREAD

**Issue by feng99** [chuan-yun/Molten#157]
您好，
我的项目是
phalcon框架➕swoole4.0
未使用协程。
rpc部分用的是鸟哥的yar+swoole

想实现微服务架构下的全链路追踪，
网络io，之类的时间统计，目前是通过在代码中加日志，存储到es实现的

2.是否与其他扩展冲突，比如xhprof

**Comment by feng99** [comment]
特别是，服务A调用服务B，整个请求跨进程了，但是要保证顺序性，也要保证时序性，还有就是服务调用的深度，
比如a调用b，b又调用c，深度为2.这样子。

静待回复，谢谢。

**Comment by silkcutKs** [comment]
目前来看实现不了，如果是swoole的可以看看他们自己推出的swooleTracker
https://business.swoole.com/tracker/index

**Comment by feng99** [comment]
感谢您的回复.    
那我通过记录日志的方式   自己实现吧.   
日志组件  使用seaslog 开启buffer  
对性能影响应该很小.
