### ISSUE TITLE
执行sh run.sh的时候开始下载jar文件

### ISSUE THREAD

**Issue by banditsmile** [chuan-yun/Molten#16]
执行sh run.sh的时候开始下载jar文件，而且这个文件有51m，我只有不到20k的下载速度，这个能否提前预告一下？
![wx20170808-105233](https://user-images.githubusercontent.com/2239356/29054298-f0113cb2-7c27-11e7-97dc-84ab44ab8980.png)

**Comment by silkcutKs** [comment]
确实是的， 例子中需要下载zipin server的，我会在之后wiki仔细说明一下。

**Comment by silkcutKs** [comment]
示例启动参照：
https://github.com/chuan-yun/Molten/wiki/Example
