### ISSUE TITLE
Temp usage issue

### ISSUE THREAD

**Issue by remicollet** [chuan-yun/Molten#28]
In molten_lock.h

`    char lock_path[LOCK_PATH_SIZE];`

So lock_path is always set

In molten_lock.h

`    if (lock->lock_path == NULL) {`

So this condition is always false.

`        mktemp(lock->lock_path);       `

mktemp is unsecure and should not be used

```
$ man 3 mktemp
       Never use this function; see BUGS.
$ make
...
/work/GIT/Molten/common/molten_lock.c:147: warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
```

Proposal: use `php_open_temporary_fd_ex` public PHP API.

**Comment by silkcutKs** [comment]
the error already fix.
the common dir will be used for cli tool feature, cli tool will not be compiled with php ,  so public PHP API should not be used in it.
