### ISSUE TITLE
支持mac系统吗？

### ISSUE THREAD

**Issue by yunnanwenshan** [chuan-yun/Molten#31]
错误信息:
172-15-70-72:Molten-0.1.0 admin$ ./configure
172-15-70-72:Molten-0.1.0 admin$ make
/bin/sh /Users/admin/opt/php/Molten-0.1.0/libtool --mode=compile cc  -I. -I/Users/admin/opt/php/Molten-0.1.0 -DPHP_ATOM_INC -I/Users/admin/opt/php/Molten-0.1.0/include -I/Users/admin/opt/php/Molten-0.1.0/main -I/Users/admin/opt/php/Molten-0.1.0 -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/include -I/Users/admin/opt/php/Molten-0.1.0 -I/Users/admin/opt/php/Molten-0.1.0/common  -DHAVE_CONFIG_H  -g -O2   -c /Users/admin/opt/php/Molten-0.1.0/molten.c -o molten.lo
 cc -I. -I/Users/admin/opt/php/Molten-0.1.0 -DPHP_ATOM_INC -I/Users/admin/opt/php/Molten-0.1.0/include -I/Users/admin/opt/php/Molten-0.1.0/main -I/Users/admin/opt/php/Molten-0.1.0 -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/include -I/Users/admin/opt/php/Molten-0.1.0 -I/Users/admin/opt/php/Molten-0.1.0/common -DHAVE_CONFIG_H -g -O2 -c /Users/admin/opt/php/Molten-0.1.0/molten.c  -fno-common -DPIC -o .libs/molten.o
In file included from /Users/admin/opt/php/Molten-0.1.0/molten.c:24:
In file included from ./php_molten.h:36:
In file included from ./molten_intercept.h:33:
/usr/local/include/php/ext/mysqli/php_mysqli_structs.h:63:10: fatal error: 'my_global.h' file not found
#include <my_global.h>
         ^
1 error generated.
make: *** [molten.lo] Error 1

my_global.h文件路径：
172-15-70-72:Molten-0.1.0 admin$ ls /usr/local/include/mysql/
big_endian.h                m_ctype.h                   my_dir.h                    mysql/                      mysqld_error.h              plugin_keyring.h            thr_mutex.h
binary_log_types.h          m_string.h                  my_getopt.h                 mysql.h                     mysqlx_ername.h             plugin_validate_password.h  thr_rwlock.h
byte_order_generic.h        my_alloc.h                  my_global.h                 mysql_com.h                 mysqlx_error.h              sql_common.h                typelib.h
byte_order_generic_x86.h    my_byteorder.h              my_list.h                   mysql_com_server.h          mysqlx_version.h            sql_state.h
decimal.h                   my_command.h                my_sys.h                    mysql_embed.h               plugin.h                    sslopt-case.h
errmsg.h                    my_compiler.h               my_thread.h                 mysql_time.h                plugin_audit.h              sslopt-longopts.h
keycache.h                  my_config.h                 my_thread_local.h           mysql_version.h             plugin_ftparser.h           sslopt-vars.h
little_endian.h             my_dbug.h                   my_xml.h                    mysqld_ername.h             plugin_group_replication.h  thr_cond.h

**Comment by silkcutKs** [comment]
支持mac系统的， 这个问题应该是编译中引入php依赖库导致的， 我这两天修复一下。(或者你可以安装一下mysql的依赖库，来解决一下这个问题)

**Comment by silkcutKs** [comment]
尝试使用一下最新的分支， 添加了mysqlnd 的检查和编译选项

**Comment by php-cpm** [comment]
试试用homebrew安装
```
brew tap php-cpm/php
brew install php56-molten
```
