### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by magnetoeric** [chuan-yun/Molten#34]
--with-mysql　指定值后报错，默认不会报错，默认是mysqlnd吧，
--with-mysqli=/usr/bin/mysql_config

/usr/local/php5.5/include/php/ext/mysqli/php_mysqli_structs.h:63:23: fatal error: my_global.h: 没有那个文件或目录

**Comment by silkcutKs** [comment]
@magnetoeric   你拉取的是最新master的代码吗？？

**Comment by silkcutKs** [comment]
下面是我的配置：
'./configure'  '--prefix=/usr/local/php5.4.16-mysql' '--with-bz2' '--disable-all' '--enable-cli' '--enable-cgi' '--enable-sockets' '--with-curl' '--with-zlib' '--enable-zip' '--enable-pdo' '--with-mysql=mysqlnd' '--with-mysqli=/usr/bin/mysql_config' '--with-pdo-mysql=mysqlnd' '--enable-json=shared' '--with-pcre-regex' '--enable-spl' '--with-pear' '--enable-xml' '--enable-libxml'
拉取最新的master编译是没有问题的。

**Comment by magnetoeric** [comment]
--enable-mysqlnd --prefix=/usr/local/php5.5 --with-config-file-scan-dir=/usr/local/php/conf.d --enable-bcmath --enable-calendar --enable-dba --enable-mbstring --enable-shmop --enable-soap --enable-sockets --enable-sysvmsg --enable-zip --with-gd --with-xmlrpc --enable-zend-signals --with-pdo-mysql --with-bz2 --with-zlib --with-openssl --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --with-curl --enable-sysvshm --enable-sysvsem --with-mysqli=/usr/bin/mysql_confi

**Comment by silkcutKs** [comment]
@magnetoeric  你下载最新的master尝试了吗？？

**Comment by magnetoeric** [comment]
试了　更新master了

**Comment by magnetoeric** [comment]
清了一下链接文件　重新编译　通过了　谢谢
