### ISSUE TITLE
可以像xhprof一样，提供个开关功能和允许返回上报数据吗

### ISSUE THREAD

**Issue by reynaldliu** [chuan-yun/Molten#43]
可以像xhprof一样，提供个开关功能和返回值吗
像这样。
molten_enable();

$molten_span_data=molten_disable();

molten.sink_type=7//   函数返回
通过代码自身来获取分析结果数据。相比stdout直接输出，可以在代码里更好格式化或追加其他字段。

**Comment by silkcutKs** [comment]
这个和xhprof的定位是不太一样的， 添加定制化的字段和格式化， 不利于后端固定的格式的分析。
