### ISSUE TITLE
”Cannot decode spans“

### ISSUE THREAD

**Issue by ycaihappy** [chuan-yun/Molten#45]
使用配置

molten.sink_type=4
molten.output_type = 2
molten.sink_http_uri = 'http://127.0.0.1:9411/api/v1/spans'

**Comment by silkcutKs** [comment]
设置为  molten.output_type = 1 
molten.output_type 会分行

**Comment by ycaihappy** [comment]
我在使用hprose集成的时候，发现如下几个问题
1.无论请求多少个服务，都只获取到一个service。举个例子

> 
> $client = Client::create('http://192.168.52.139/HttpServer.php', false);
> var_dump($client->init());
> var_dump($client->payment());

2. service我可以自定义吗？比如一个支付过程，分为初始化，支付，其实我通过rpc调用服务，现在看起来只会记录一条。。这个不知道有没有什么好的解决方法。
