### ISSUE TITLE
是否考虑支持类似hprose的rpc服务

### ISSUE THREAD

**Issue by ycaihappy** [chuan-yun/Molten#46]
一直在找php的链路跟踪方案，有幸找到了这个。基本上现在跑通了，谢谢你们的劳动。
我在使用hprose集成的时候，发现如下几个问题
1.无论请求多少个服务，都只获取到一个service。举个例子

> 
> $client = Client::create('http://192.168.52.139/HttpServer.php', false);
> $client->init();
> $client->payment();

2. service例子都是一样的，我如果要区分，必须要把所有的拆分成curl调用吗？我可以自定义吗？比如一个支付过程，分为初始化，支付等，目前通过rpc调用服务，现在看起来只会记录一条。。这个不知道有没有什么好的解决方法。

**Comment by silkcutKs** [comment]
1 对于rpc服务单纯的拦截，问题不大， 但是想要将信息串联起来需要rpc服务的协议能够支持。

2 这个hprose rpc 没有研究过， 我看看之后再给你一个结论
