### ISSUE TITLE
/molten/status访问不到

### ISSUE THREAD

**Issue by ycaihappy** [chuan-yun/Molten#47]
我是使用PHP -S 启动的本地服务器，使用

http://192.168.52.139/molten/status 无法查看到相关信息，什么原因啊？谢谢

**Comment by silkcutKs** [comment]
molten进行uri拦截是在扩展request_init 流程中做的。
而php的cli_server 和fpm 执行流程不一致。
cli_server -> php_cli_server_dispatch ， 中判断非静态文件的时候 才会调用php_cli_server_request_startup。 在php_cli_server_request_startup中会调用各个扩展的reqeust_init流程。
而如果cli_server判断是静态文件，会直接走到静态文件执行流程中，不会调用扩展的request_init流程。 

这个功能在cli_server不会起作用。

**Comment by ycaihappy** [comment]
我的molten/status

# HELP molten_request_all Number of all request.
# TYPE molten_request_all counter
molten_request_all 63
# HELP molten_request_capture Number of request be capture.
# TYPE molten_request_capture counter
molten_request_capture 63
# HELP molten_sampling_type the type of sampling.
# TYPE molten_sampling_type gauge
molten_sampling_type 2
# HELP molten_sampling_rate the rate of sampling.
# TYPE molten_sampling_rate gauge
molten_sampling_rate 1
# HELP molten_sampling_request the request be capture one min.
# TYPE molten_sampling_request gauge
molten_sampling_request 100
# HELP molten_version current molten span version.
# TYPE molten_version gauge
molten_version php-4

这里最后一行php-4是啥含义？我现在升级到php71后，看到的还是php-4的东西？并且往zipkin写不入数据了？

**Comment by silkcutKs** [comment]
@ycaihappy  请贴一下 配置
https://github.com/chuan-yun/Molten/wiki/Q&A  请按照这个排查一下
