### ISSUE TITLE
采样率现在是否有问题？

### ISSUE THREAD

**Issue by maxincai** [chuan-yun/Molten#48]
我测试的时候，已经设置了molten.sampling_rate=1，但还是有只有比较小的机会才会输出。
php -d extension=molten.so -d molten.enable=1 -d molten.sink_type=2 -d molten.tracing_cli=1 -d molten.sampling_rate=1 -r '$c=curl_init("http://localhost:12345");curl_exec($c);'

**Comment by maxincai** [comment]
php版本信息：

```
'./configure' '--prefix=/usr/local/php5.6.28' '--enable-fpm' '--enable-cgi' '--enable-mbstring' '--enable-pdo' '--enable-soap' '--enable-xml' '--enable-libxml' '--enable-zip' '--enable-mysqlnd' '--enable-sockets' '--enable-json' '--with-gd' '--with-jpeg-dir' '--with-png-dir' '--with-mcrypt' '--with-curl' '--with-iconv' '--with-zlib' '--with-pear' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--with-openssl' '--enable-opcache' '--enable-bcmath' '--enable-inline-optimization' '--enable-gd-native-ttf' '--enable-pcntl' '--disable-ipv6' '--with-mhash' '--enable-debug' '--with-freetype-dir'
--
```

**Comment by maxincai** [comment]
![image](https://user-images.githubusercontent.com/5461715/32322206-b99fc722-bf91-11e7-8a12-cdaf6ac60e8d.png)

**Comment by silkcutKs** [comment]
你的同一台机器上，是否已经启动了php-fpm?

**Comment by maxincai** [comment]
启动了 php-fpm

配置：
[molten]
extension=molten.so
molten.sink_type=1
molten.sampling_rate=1
molten.sink_log_path=/var/log/nginx/tracing
molten.sink_http_uri=http://127.0.0.1:9411/api/v1/spans

**Comment by silkcutKs** [comment]
当前版本中molten中部分控制信息是采用共享内存的方式来完成， 因此一旦在当前机器上启动php-fpm了， phpcli会采用php-fpm中配置内容， 这一部分的内容包括采样率的控制。
用phpcli模式运行的时候， 建议将php-fpm关闭

**Comment by reynaldliu** [comment]
看这个坑很多人都在踩。不如把共享内存的键名和清除方法加到demo初始化命令里。每次example开始前清除一次。

**Comment by silkcutKs** [comment]
在php cli模式下 不采用共享内存中的信息， 这样是不是更好一些？ 你认为如何？

**Comment by maxincai** [comment]
我觉得可以，在php cli 模式下单独处理。

**Comment by silkcutKs** [comment]
@maxincai   master 分支已经将这个问题修复了。

**Comment by maxincai** [comment]
@silkcutKs 重新下载编译后已经可以了，感谢。
