### ISSUE TITLE
centos下使用yum安装php7+nginx时，molten的扩展会导致php-fpm启动时报错

### ISSUE THREAD

**Issue by ycaihappy** [chuan-yun/Molten#49]
yum安装包如下
php71-php-pecl-molten.x86_64 : Extension for application tracing
php72-php-pecl-molten.x86_64 : Extension for application tracing

启动php-fpm时报错，错误如下:

Job for php71-php-fpm.service failed because the control process exited with error code. See "systemctl status php71-php-fpm.service" and "journalctl -xe" for details.

yum删除molten安装，启动正常。

phpzie编译扩展暂时还没试。

**Comment by silkcutKs** [comment]
@ycaihappy  你是用得remi的yum 源吗？

**Comment by ycaihappy** [comment]
后面用phpzie编译源码安装成功了。下面之前安装失败的rpm包信息，貌似是beta版本的

[root@localhost ~]# yum info php71-php-pecl-molten.x86_64
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * epel: mirrors.ustc.edu.cn
 * extras: mirrors.163.com
 * remi-safe: mirrors.tuna.tsinghua.edu.cn
 * updates: mirrors.aliyun.com
Available Packages
Name        : php71-php-pecl-molten
Arch        : x86_64
Version     : 0.1.2~beta
Release     : 2.el6.remi
Size        : 51 k
Repo        : remi-safe
Summary     : Extension for application tracing
URL         : http://pecl.php.net/package/molten
License     : ASL 2.0
Description : Molten is transparency tool for application tracing it self module call.
            :
            : It trace php app core call and output zipkin/opentracing format trace log.
            :
            : Provides features about muliti trace sapi, multi sampling type,
            : upload tracing status, module control and muliti sink type.
            :
            : It very easy to build a distributed systems tracing infrastructure base
            : on php, already run on thousand instance on production env.
            :
            : Package built for PHP 7.1 as Software Collection (php71 by remi).

**Comment by silkcutKs** [comment]
我在pecl上重新发布一个release 包， 可能之前的php71包存在问题

**Comment by ycaihappy** [comment]
重新安装后，启动php-fpm正常。
