### ISSUE TITLE
编译不了，报错

### ISSUE THREAD

**Issue by Leon2012** [chuan-yun/Molten#5]
环境:
vagrant&ubuntu14.04 & php5.6.29

错误信息:
In file included from /home/vagrant/Molten/molten_intercept.c:18:0:
/usr/local/webserver/php5629/include/php/ext/mysqli/php_mysqli_structs.h:63:23: fatal error: my_global.h: No such file or directory

**Comment by silkcutKs** [comment]
php -i | grep configure 贴一下吧， 
其中有mysqli扩展吗？

编译PHP时，./configure参数中务必要加入

 --enable-mysqlnd --with-mysqli

**Comment by silkcutKs** [comment]
问题出在这里：
#ifdef MYSQLI_USE_MYSQLND
 #include "ext/mysqlnd/mysqlnd.h"
 #include "mysqli_mysqlnd.h"
 #else

 /*
   The libmysql headers (a PITA) also define it and there will be an warning.
   Undef it and later we might need to define it again.
 */
 #ifdef HAVE_MBRLEN
 #undef HAVE_MBRLEN
 #define WE_HAD_MBRLEN
 #endif
 #ifdef HAVE_MBSTATE_T
 #undef HAVE_MBSTATE_T
 #define WE_HAD_MBSTATE_T
 #endif

 #if defined(ulong) && !defined(HAVE_ULONG)
 #define HAVE_ULONG
 #endif

 #include <my_global.h>

 #if !defined(HAVE_MBRLEN) && defined(WE_HAD_MBRLEN)
 #define HAVE_MBRLEN 1
 #endif

没有使用mysqlnd， 并且在机器上也没有libmysql的编译环境，所以出问题了

**Comment by yyork** [comment]
@silkcutKs 
环境 macOS 10.12.6 & php7.1.7

错误信息:
In file included from /Users/york/Downloads/Molten/molten.c:24:
In file included from ./php_molten.h:35:
In file included from ./molten_chain.h:34:
./molten_log.h:31:10: fatal error: 'error.h' file not found
#include <error.h>
         ^
1 error generated.
make: *** [molten.lo] Error 1

**Comment by silkcutKs** [comment]
@yyork 我来处理一下

**Comment by silkcutKs** [comment]
@Leon2012 没有mysqlnd 也可以build通过了。
@yyork macos 上build已经支持，可以尝试build了

**Comment by yyork** [comment]
@silkcutKs 谢谢，已build成功。
