### ISSUE TITLE
curl 报错误

### ISSUE THREAD

**Issue by liugj** [chuan-yun/Molten#50]
Cannot decode spans

**Comment by silkcutKs** [comment]
at what phase?

**Comment by liugj** [comment]
cd  example;sh run.sh

**Comment by silkcutKs** [comment]
i can not repeat the problem on my machine,.
if your machine  env is not pure, please paste  your molten config.

**Comment by liugj** [comment]
我知道问题了  curl -H "Expect:" -H "Content-Type:application/json" -d '[{"traceId":"203e61853bd419ee","name":"php_curl","version":"php-4","id":"1.1","timestamp":1510299948487949,"duration":5336,"annotations":[{"value":"cs","timestamp":1510299948487949,"endpoint":{"serviceName":"php_test","ipv4":"10.0.2.15"}},{"value":"cr","timestamp":1510299948493285,"endpoint":{"serviceName":"php_test","ipv4":"10.0.2.15"}}],"binaryAnnotations":[{"key":"http.url","value":"http://localhost:12345/","endpoint":{"serviceName":"php_test","ipv4":"10.0.2.15"}},{"key":"error","value":"Failed to connect to localhost port 12345: Connection refused","endpoint":{"serviceName":"php_test","ipv4":"10.0.2.15"}}]},{"traceId":"203e61853bd419ee","name":"cli","version":"php-4","id":"1","timestamp":1510299948487872,"duration":5476,"annotations":[{"value":"sr","timestamp":1510299948487872,"endpoint":{"serviceName":"php_test","ipv4":"10.0.2.15"}},{"value":"ss","timestamp":1510299948493348,"endpoint":{"serviceName":"php_test","ipv4":"10.0.2.15"}}],"binaryAnnotations":[{"key":"path","value":"-","endpoint":{"serviceName":"php_test","ipv4":"10.0.2.15"}}]}]' http://127.0.0.1:9411/api/v1/spans
molten 生成的内容中“”id” 和parentId 的长度不是16位

**Comment by silkcutKs** [comment]
这个是你编译的时候添加了  --enable-level-id 这个选项吧，level id 是链路等级id 。
像zipkin server 是分析不了 这种id的。

**Comment by liugj** [comment]
是的，我去掉这个选项就好，非常感谢！

**Comment by liugj** [comment]
ini_set('molten.service_name', 'openapi-shop'); 后  serviceName 还是default


[
    {
        "traceId": "fb350bac8e703f24",
        "name": "php_curl",
        "version": "php-4",
        "id": "8a4748ed9d2bd2b3",
        "parentId": "b13e0b71fb4cddbf",
        "timestamp": 1510646773813501,
        "duration": 5537,
        "annotations": [
            {
                "value": "cs",
                "timestamp": 1510646773813501,
                "endpoint": {
                    **"serviceName": "default",**
                    "ipv4": "10.0.2.15"
                }
            },
            {
                "value": "cr",
                "timestamp": 1510646773819038,
                "endpoint": {
                    "serviceName": "default",
                    "ipv4": "10.0.2.15"
                }
            }
        ],
        "binaryAnnotations": [
            {
                "key": "http.url",
                "value": "http://localhost:1234/",
                "endpoint": {
                    "serviceName": "default",
                    "ipv4": "10.0.2.15"
                }
            },
            {
                "key": "error",
                "value": "Failed to connect to localhost port 1234: Connection refused",
                "endpoint": {
                    "serviceName": "default",
                    "ipv4": "10.0.2.15"
                }
            }
        ]
    },
    {
        "traceId": "fb350bac8e703f24",
        "name": "cli",
        "version": "php-4",
        "id": "b13e0b71fb4cddbf",
        "timestamp": 1510646773812835,
        "duration": 6328,
        "annotations": [
            {
                "value": "sr",
                "timestamp": 1510646773812835,
                "endpoint": {
                  "serviceName": "default",
                    "ipv4": "10.0.2.15"
                }
            },
            {
                "value": "ss",
                "timestamp": 1510646773819163,
                "endpoint": {
                    "serviceName": "default",
                    "ipv4": "10.0.2.15"
                }
            }
        ],
        "binaryAnnotations": [
            {
                "key": "path",
                "value": "/home/vagrant/Code/openapi/shop/public/info.php",
                "endpoint": {
                    "serviceName": "default",
                    "ipv4": "10.0.2.15"
                }
            }
        ]
    }
]

**Comment by silkcutKs** [comment]
@liugj   问题已经修复了。

**Comment by liugj** [comment]
谢谢啦！
