### ISSUE TITLE
关于molten/status中字段的含义

### ISSUE THREAD

**Issue by ycaihappy** [chuan-yun/Molten#54]
# HELP molten_request_all Number of all request.
# TYPE molten_request_all counter
molten_request_all 44
# HELP molten_request_capture Number of request be capture.
# TYPE molten_request_capture counter
molten_request_capture 44
# HELP molten_sampling_type the type of sampling.
# TYPE molten_sampling_type gauge
molten_sampling_type 2
# HELP molten_sampling_rate the rate of sampling.
# TYPE molten_sampling_rate gauge
molten_sampling_rate 1
# HELP molten_sampling_request the request be capture one min.
# TYPE molten_sampling_request gauge
molten_sampling_request 100
# HELP molten_version current molten span version.
# TYPE molten_version gauge
molten_version php-4

这里的molten_version指什么？我使用的是PHP71,谢谢

**Comment by silkcutKs** [comment]
这个version 指的是探针协议版本， 当前可以忽略。
