### ISSUE TITLE
PHP71 cli执行run.sh无法写入zipkin

### ISSUE THREAD

**Issue by ycaihappy** [chuan-yun/Molten#55]
php71 -d molten.enable=1 -d molten.sink_type=4 -d molten.tracing_cli=1 -d molten.sink_http_uri=http://127.0.0.1:9411/api/v1/spans -d molten.service_name=php_test -d molten.sampling_rate=1 -r '$c=curl_init("http://10.11.4.55");curl_exec($c);'

zipkin启动命令行，并且创建了相应的数据
java -jar zipkin.jar --STORAGE_TYPE=mysql --MYSQL_DB=zipkindb --MYSQL_USER=root --MYSQL_PASS=xxx --MYSQL_HOST=127.0.0.1--MYSQL_TCP_PORT=3306

开始以为是php-fpm启动的原因，停掉后执行还是写不进去zipkin。

另外，我使用nginx+php-fpm(php7)环境时，也是无法写数据到zipkin,低版本的php5.6当时测试时是没有问题的。我的molten配置如下
 molten.enable = 1
 molten.sink_log_path = '/tmp/tracing'
 molten.service_name = 'xxx'
 molten.tracing_cli = 1
 molten.sampling_type = 2
 molten.sampling_request = 100
 molten.sampling_rate = 1
 molten.span_format = 'zipkin'
 molten.report_interval = 60
 molten.notify_uri = ''
 molten.report_limit = 100
 molten.sink_type = 4
 molten.output_type = 1
 molten.sink_http_uri = 'http://127.0.0.1:9411/api/v1/spans'
 molten.sink_syslog_unix_socket = ''
 molten.sink_kafka_brokers= ''
 molten.sink_kafka_topic = ''

**Comment by silkcutKs** [comment]
你这台机器上 有libcurl-devel吗？

**Comment by ycaihappy** [comment]
[root@localhost Molten]# rpm -qa | grep libcurl
libcurl-7.29.0-35.el7.centos.x86_64

需要安装devel，为什么低版本的时候没问题？

**Comment by silkcutKs** [comment]
低版本的机器 应该是你在机器上安装libcurl-devel

**Comment by ycaihappy** [comment]
我输出到文本是有输出的

[root@localhost Molten]# php -d molten.enable=1 -d molten.sink_type=2 -d molten.tracing_cli=1 -d molten.sampling_rate=1 -r '$c=curl_init("http://localhost:12345");curl_exec($c);'
[{"traceId":"cff542c6de24be33","name":"php_curl","version":"php-4","id":"8526350c20060382","parentId":"7e3c1ef2559acedb","timestamp":1510889020762472,"duration":5391,"annotations":[{"value":"cs","timestamp":1510889020762472,"endpoint":{"serviceName":"payment","ipv4":"192.168.52.139"}},{"value":"cr","timestamp":1510889020767863,"endpoint":{"serviceName":"payment","ipv4":"192.168.52.139"}}],"binaryAnnotations":[{"key":"http.url","value":"http:\/\/localhost:12345\/","endpoint":{"serviceName":"payment","ipv4":"192.168.52.139"}},{"key":"error","value":"Failed connect to localhost:12345; Connection refused","endpoint":{"serviceName":"payment","ipv4":"192.168.52.139"}}]},{"traceId":"cff542c6de24be33","name":"cli","version":"php-4","id":"7e3c1ef2559acedb","timestamp":1510889020762248,"duration":5661,"annotations":[{"value":"sr","timestamp":1510889020762248,"endpoint":{"serviceName":"payment","ipv4":"192.168.52.139"}},{"value":"ss","timestamp":1510889020767909,"endpoint":{"serviceName":"payment","ipv4":"192.168.52.139"}}],"binaryAnnotations":[{"key":"path","value":"-","endpoint":{"serviceName":"payment","ipv4":"192.168.52.139"}}]}]

**Comment by silkcutKs** [comment]
@ycaihappy  安装完了之后需要你重新编译一下， 才能正常使用。

**Comment by ycaihappy** [comment]
php71编译后还是不行，我用php56测试时可以正常写入。php56使用的是php56-php-pecl-molten-0.1.2~beta-2.el6.remi.x86_64安装

php56 -d molten.enable=1 -d molten.sink_type=4 -d molten.tracing_cli=1 -d molten.sink_http_uri=http://127.0.0.1:9411/api/v1/spans -d molten.service_name=php_test -d molten.sampling_rate=1 -r '$c=curl_init("http://localhost:12345");curl_exec($c);'

php71 -d molten.enable=1 -d molten.sink_type=4 -d molten.tracing_cli=1 -d molten.sink_http_uri=http://127.0.0.1:9411/api/v1/spans -d molten.service_name=php_test -d molten.sampling_rate=1 -r '$c=curl_init("http://localhost:12345");curl_exec($c);'

**Comment by ycaihappy** [comment]
已经可以了，使用php71-php-pecl-molten-0.1.2~beta-2.el6.remi.x86_64安装就好了。

phpize源码编译安装的不行。
