### ISSUE TITLE
请求后，上报记录spanId重复，是什么原因造成的呢

### ISSUE THREAD

**Issue by zefengguo** [chuan-yun/Molten#62]
![qq 20180104155134](https://user-images.githubusercontent.com/13267262/34554748-5c2319fa-f169-11e7-9cd7-ff0b9708c687.png)

**Comment by zefengguo** [comment]
![qq 20180104155305](https://user-images.githubusercontent.com/13267262/34554812-c064dcaa-f169-11e7-935f-3dccf51e7ffc.png)

**Comment by silkcutKs** [comment]
如果着两个span分别对应着http的 client side 和server side是没有问题的。
client的span 和server的span组合在一起才是一个完整的span。
cs --> sr
           |
 cr<---ss
调用过程简单如上图:

**Comment by zefengguo** [comment]
好，了解，谢谢！
