### ISSUE TITLE
undefined symbol: php_pdo_get_exception in Unknown on line 0

### ISSUE THREAD

**Issue by daiqichun** [chuan-yun/Molten#63]
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/Molten-master/modules/molten.so' - /home/Molten-master/modules/molten.so: undefined symbol: php_pdo_get_exception in Unknown on line 0

php_pdo_get_exception这个方法没有定义怎么回事，我按照方法安装了，还是报错，能提供个微信群吗

**Comment by daiqichun** [comment]
我的是PHP Version 7.1.11，linux

**Comment by daiqichun** [comment]
编译中没有发现错误，就是molten.so添加扩展，好像不成功

**Comment by silkcutKs** [comment]
@daiqichun  等我下一个php7.1.11编译一下看看是否存在问题。

**Comment by silkcutKs** [comment]
@daiqichun  你贴一下你的php -m输出

**Comment by daiqichun** [comment]
我把/etc/php.d/molten.ini 改为 z_molten.ini  按照abc字母顺序，往后排，优先加载其他扩展，最终
molten support | enabled 有正常显示扩展了

**Comment by silkcutKs** [comment]
在一些php编译选项和操作系统中是存在这个问题的, 详细内容可以参照这里。
https://derickrethans.nl/undefined-symbol.html

**Comment by schien-dong** [comment]
I experienced a similar issue with another PDO driver - it's important to load the extension AFTER the main PDO extension. For example, change /etc/php/7.1/mods-available/pdo.ini, and find this line:

extension=pdo.so

Then add:
extension=molten.so

Good luck!

**Comment by silkcutKs** [comment]
resolved
