### ISSUE TITLE
cli模式下PHP脚本内存会暴增？

### ISSUE THREAD

**Issue by kcloze** [chuan-yun/Molten#71]
cli大批量数据操作和较长时间业务逻辑，不开启molten扩展没有问题，开启之后内存超过限制，怀疑molten开启之后，会大大增大内存消耗

猜测是调用时都会记录一些信息，cli大脚本不进入request end阶段导致内存迟迟没回收

**Comment by kcloze** [comment]
有没有可以主动flush日志的功能，这样确保log信息内存占用不会爆栈？

**Comment by silkcutKs** [comment]
@kcloze  你说的对，其实现在不推荐使用cli 模式下使用molten。 
现阶段molten没有支持 kafka等的消费端， 添加cli之后意义不大。

**Comment by kcloze** [comment]
可以考虑增加一个配置开关，可以在代码或者配置文件里面忽略molten扩展，因为有可能cli和fpm是公用php.ini的

**Comment by silkcutKs** [comment]
@kcloze  存在开关的  molten.tracing_cli=0

**Comment by kcloze** [comment]
好的，多谢
