### ISSUE TITLE
小咨询下

### ISSUE THREAD

**Issue by kbigbus** [chuan-yun/Molten#75]
我看curl相关函数的拦截和redis pdo memcache的拦截有些差异，是否版本的迭代导致的？ 如果是，那哪种拦截方式才是通用些的呢？

**Comment by silkcutKs** [comment]
@是redis/memcache是通用的， curl是为了效率考虑才采用特殊的拦截模式， 具体代码那里你可以看到的

**Comment by kbigbus** [comment]
get  感谢
