### ISSUE TITLE
molten 采集类型

### ISSUE THREAD

**Issue by iiishine** [chuan-yun/Molten#77]
你好,请问molten 采样类型除了 1采样率 和2每分钟数,有没有可能考虑 对trace_id的响应时间做采样或存储.
我的需求是: 系统可以存储 响应时间 大于300ms的请求.

非常感谢~

**Comment by silkcutKs** [comment]
采样的概念和你提到的采集类型不一样，  你想要存储大于300ms的请求， 可以将采样率设置为1 然后将信息收集起来之后， 走后台统计。

**Comment by iiishine** [comment]
嗯,走后台统计的我知道~ 
主要是设置 molten_sampling_rate的值小的话,存储到es的数据就很大!
希望前端客户端能过滤一部分数据, 而molten_sampling_rate设置过大 可能会漏掉一些想要的trace!

如果molten.sink_type设置2,存储为文件,然后去对文件过滤然后存储到es之类,不知道可行不可行?  
暂时还是用molten.sink_type的值大小来控制存储到es的数据量的!

谢谢~

**Comment by silkcutKs** [comment]
@iiishine  你说的方式的可行， 我们一般也会做些类似的， 中间层加一些filter， 发送到不同的channel去进行分析， 只不过维度可能有些区别。

**Comment by iiishine** [comment]
@silkcutKs  嗯嗯,了解,感谢~
