### ISSUE TITLE
运行run.sh出现问题

### ISSUE THREAD

**Issue by hchengvip** [chuan-yun/Molten#81]
PHP Warning:  Module 'molten' already loaded in Unknown on line 0

出现上面的错误。怎么解决？

**Comment by silkcutKs** [comment]
@hchengvip  这个应该是本地php配置问题， 你可以先看看自己的php.ini文件中是否设置的正确。

**Comment by silkcutKs** [comment]
@hchengvip  问题解决了吗？

**Comment by claytonxia** [comment]
run.sh在php命令里面手动添加了molten拓展，所以运行run.sh和complex.sh的时候手动从php.ini中将extension=molten.so屏蔽掉，或者修改run.sh跟complex.sh脚本，后者更好
