### ISSUE TITLE
php5.2.17 可以安装molten扩展吗?

### ISSUE THREAD

**Issue by iiishine** [chuan-yun/Molten#82]
make的时候报错: 

/usr/local/src/Molten/molten_log.c: In function ‘mo_chain_log_flush’:
/usr/local/src/Molten/molten_log.c:493: error: too many arguments to function ‘php_json_encode’
/usr/local/src/Molten/molten_log.c:517: error: too many arguments to function ‘php_json_encode’

**Comment by silkcutKs** [comment]
不打算支持5.4版本之下的。
最好将php版本生级。

**Comment by iiishine** [comment]
好的,谢谢
