### ISSUE TITLE
运行run.sh，不使用自带的zipkin-server，无法上报信息UPDATE 无法设置X-B3 Header

### ISSUE THREAD

**Issue by GreedyPirate** [chuan-yun/Molten#83]
我从zipkin官网下载了一个server，已经集成好了java的相关服务追踪，想要集成php，运行molten里的example，修改run.sh如下：
#sh ./zipkin.sh

php -d extension=molten.so -d molten.enable=1 -d molten.sink_type=4 -d molten.tracing_cli=1 -d molten.sink_http_uri=http://172.15.70.249:9411/api/v2/spans -d molten.service_name=php_test -d molten.sampling_rate=1 -r '$c=curl_init("172.15.70.172:8089/zipkin");curl_exec($c);'

首先注释了 sh ./zipkin.sh ,然后修改了sink_http_uri，注意是api/v2, 感觉demo的版本没有跟上，最后修改了请求的url，打开web console，发现没有名为php_test的服务名,最后修改回去，发现一切正常，按理说我只修改了zipkin的上报地址
最后，能不能更新下wiki里的微信二维码，方便交流
@silkcutKs 

UPDATE:
虽然不知道怎么回事，在服务名列表里突然有了php_test，但是依然没有相关的trace信息，下游java服务的是trace是正常显示的

UPDATE:
如何支持B3-header? 我也按照文档./configure --enable-zipkin-header=yes, 在Config.log文件中找到
configure:4107: checking whether to enable zipkin B3 header
configure:4121: result: yes
但在我在java服务中的request header里依然显示x-w

UPDATE:
@silkcutKs 沟通成本实在太高了，能不能贴个交流群二维码

UPDATE:
找到一个临时解决办法，在molten_util.h中强制将X-W修改为X-B3
#define MOLTEN_HEADER_PREFIX "X-B3-"
#define MOLTEN_REC_HEADER_PREFIX "HTTP_X_B3_"

然后重新编译一遍，web console显示正常，done，希望给出更优雅的方案

**Comment by silkcutKs** [comment]
@GreedyPirate 
```
如何支持B3-header? 我也按照文档./configure --enable-zipkin-header=yes, 在Config.log文件中找到
configure:4107: checking whether to enable zipkin B3 header
configure:4121: result: yes
但在我在java服务中的request header里依然显示x-w
```
这个问题，可能跟你重新编译时，清理好对应编译文件有关，这个功能我这里是经过测试的。

```
找到一个临时解决办法，在molten_util.h中强制将X-W修改为X-B3
#define MOLTEN_HEADER_PREFIX "X-B3-"
#define MOLTEN_REC_HEADER_PREFIX "HTTP_X_B3_"

然后重新编译一遍，web console显示正常，done，希望给出更优雅的方案
```
文档中的./configure --enable-zipkin-header=yes 是ok。

@GreedyPirate 
请贴出一下./configure 之后生成的 config.h文件的内容。

**Comment by silkcutKs** [comment]
@GreedyPirate 群里现在人满了，你把你的email给我一下，我拉你进群把。

**Comment by GreedyPirate** [comment]
@silkcutKs 我按照你说的，重新clone，重新编译，b3-header正常，十分感谢 👍 
我的email是jaynnay@sina.com，拉我进群哈
