### ISSUE TITLE
编译时报错 error: ‘PHP_JSON_OBJECT_AS_ARRAY’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by woxinfeixiang** [chuan-yun/Molten#84]
请问现在执行make 时，报错：
error: ‘PHP_JSON_OBJECT_AS_ARRAY’ undeclared (first use in this function)

请问现在还可以解决吗

**Comment by silkcutKs** [comment]
这个应该是你编译的php版本中没有json的模块， 你检查一下。

**Comment by silkcutKs** [comment]
@woxinfeixiang  问题解决了吗？

**Comment by woxinfeixiang** [comment]
我理解错了，不过我的PHP中是支持json的模块的，我的PHP版本是5.3.29 不知道和版本有没有关系

**Comment by silkcutKs** [comment]
@woxinfeixiang  最低支持到php5.4
