### ISSUE TITLE
traces上报到本地文件失败

### ISSUE THREAD

**Issue by claytonxia** [chuan-yun/Molten#90]
当设置sink_type为1的时候，同时配置本地sink_log_path,执行完curl后文件为空,代码如下:

php -d extension=molten.so -d molten.report_interval=1 -d molten.service_name=hahahah -d molten.molten_enable=1 -d molten.sink_type=1 -d molten.sink_log_path=/var/log/molten/log -d molten.tracing_cli=1 -d molten.sampling_type=2 -d molten.sampling_request=1000 -r 'curl_exec(curl_init("http://localhost:78945"));'

**Comment by kbigbus** [comment]
@claytonxia  老铁 ，能说明一波不？    我这边也是没有任何报错，也没有任何日志产生。
