### ISSUE TITLE
Upgrade to version 2 zipkin format?

### ISSUE THREAD

**Issue by adriancole** [chuan-yun/Molten#93]
It seems likely that we are having issues due to data format here: https://github.com/apache/incubator-skywalking/issues/1495#issuecomment-408727598

Can you consider moving to v2 format or using https://github.com/openzipkin/zipkin-php? It is easy for people to get this wrong.. many use v2 by default. Eventhough the server can read both formats, people get the endpoint wrong.

**Comment by silkcutKs** [comment]
already support zipkin v2 format, user can set `molten.span_format=zipkin_v2`

**Comment by silkcutKs** [comment]
resolved
